# Generated by Django 3.0.8 on 2020-08-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0010_auto_20200810_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OT_Honoraire', models.IntegerField(blank=True, default=0, null=True)),
                ('Autres_Montant', models.IntegerField(blank=True, default=0, null=True)),
                ('BAD_Montant', models.IntegerField(blank=True, default=0, null=True)),
                ('Overstay_Montant', models.IntegerField(blank=True, null=True)),
                ('Surestaries_Montant', models.IntegerField(blank=True, null=True)),
                ('Debarquement', models.IntegerField(blank=True, null=True)),
                ('Magasinage_Montant', models.IntegerField(blank=True, null=True)),
                ('Droit_Compromis', models.IntegerField(blank=True, null=True)),
                ('Amende_Montant', models.IntegerField(blank=True, null=True)),
                ('OV_Montant', models.IntegerField(blank=True, null=True)),
                ('OV_Docker', models.IntegerField(blank=True, null=True)),
                ('Montant_Fret', models.IntegerField(blank=True, null=True)),
                ('Immobilisation', models.IntegerField(blank=True, null=True)),
                ('Num_Facture', models.CharField(blank=True, max_length=50)),
                ('Nom_Client', models.CharField(blank=True, max_length=500)),
                ('Adresse_Client', models.CharField(blank=True, max_length=500)),
                ('Contact_Client', models.CharField(blank=True, max_length=500)),
                ('email_client', models.EmailField(blank=True, max_length=500)),
                ('Date_Facture', models.DateField(auto_now=True)),
                ('SousTotal', models.IntegerField(blank=True, null=True)),
                ('Tax', models.IntegerField(blank=True, null=True)),
                ('TotalFacture', models.IntegerField(blank=True, null=True)),
                ('idOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Operation')),
            ],
        ),
    ]
