# Generated by Django 3.0.8 on 2020-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureoperation',
            name='Date_Facture',
            field=models.DateField(blank=True),
        ),
    ]
