# Generated by Django 3.1 on 2020-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_facturemoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureoperation',
            name='Ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
