# Generated by Django 3.0.8 on 2020-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Montant_Fret',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
