# Generated by Django 3.0.8 on 2020-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20200802_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
