# Generated by Django 3.0.8 on 2020-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20200808_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_Operation',
            field=models.CharField(blank=True, choices=[('Importation', 'Importation'), ('Exportation', 'Exportation')], max_length=50),
        ),
    ]
