# Generated by Django 3.0.8 on 2020-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20200809_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Circuit',
            field=models.CharField(blank=True, choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('rouge', 'Rouge')], max_length=20, null=True),
        ),
    ]
