# Generated by Django 3.0.8 on 2020-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20200809_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Amende_Mode_Paiement',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Virement banquaire', 'Virement banquaire'), ('Cheque', 'Cheque'), ('Western Union', 'Western Union'), ('MVola', 'MVola')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='DC_Mode_Paiement',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Virement banquaire', 'Virement banquaire'), ('Cheque', 'Cheque'), ('Western Union', 'Western Union'), ('MVola', 'MVola')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='OV_Num_Compte',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
