# Generated by Django 3.0.8 on 2020-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20200810_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Prep_Full',
            field=models.BooleanField(default=False),
        ),
    ]
