# Generated by Django 3.0.8 on 2020-08-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20200810_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Facture_Adresse_Client',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Amende_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Autres_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_BAD_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Contact_Client',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Date_Facture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Debarquement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Droit_Compromis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Immobilisation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Magasinage_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Montant_Fret',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Nom_Client',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Num_Facture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_OT_Honoraire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_OV_Docker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_OV_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Overstay_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_SousTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_Surestaries_Montant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='Facture_email_client',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operation',
            name='Tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='TotalFacture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
