# Generated by Django 3.1 on 2020-09-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Moto', models.IntegerField(blank=True, null=True, unique=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('nom_moto', models.CharField(max_length=500)),
                ('num_moteur', models.CharField(max_length=500, unique=True)),
                ('FRN', models.CharField(blank=True, max_length=500)),
                ('PA', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('PV', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_vente', models.DateField(null=True)),
                ('nom_client_1', models.CharField(blank=True, max_length=50)),
                ('CIN_Num_Client_1', models.CharField(blank=True, max_length=50)),
                ('PJ_CIN_Client_1_recto', models.FileField(blank=True, null=True, upload_to='images')),
                ('PJ_CIN_Client_1_verso', models.FileField(blank=True, null=True, upload_to='images')),
                ('tel_client_1', models.CharField(blank=True, max_length=50)),
                ('adresse_client_1', models.CharField(blank=True, max_length=50)),
                ('num_BL', models.IntegerField(null=True, unique=True)),
                ('num_sur_facture', models.IntegerField(null=True, unique=True)),
                ('PJ_Facture', models.FileField(blank=True, null=True, upload_to='images')),
                ('nom_client_2', models.CharField(blank=True, max_length=50)),
                ('tel_client_2', models.CharField(blank=True, max_length=50)),
                ('adresse_client_2', models.CharField(blank=True, max_length=50)),
                ('CIN_Num_Client_2', models.CharField(blank=True, max_length=50)),
                ('PJ_CIN_Client_2_recto', models.FileField(blank=True, null=True, upload_to='images')),
                ('PJ_CIN_Client_2_verso', models.FileField(blank=True, null=True, upload_to='images')),
                ('montant_reparation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('motif_reparation', models.CharField(blank=True, max_length=500)),
                ('commercial', models.CharField(blank=True, max_length=500)),
                ('volume_moteur', models.CharField(blank=True, max_length=500)),
                ('PU_HT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('PT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('montant_lettre', models.CharField(blank=True, max_length=500)),
                ('Ref', models.IntegerField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
    ]
