# Generated by Django 3.0.8 on 2020-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Moto', models.IntegerField(blank=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('nom_moto', models.CharField(max_length=500)),
                ('num_moteur', models.CharField(max_length=500)),
                ('FRN', models.CharField(blank=True, max_length=500)),
                ('PA', models.IntegerField(null=True)),
                ('PV', models.IntegerField(null=True)),
                ('date_vente', models.DateField(null=True)),
                ('nom_client_1', models.CharField(blank=True, max_length=50)),
                ('PJ_CIN_Client_1_recto', models.FileField(blank=True, upload_to='images')),
                ('PJ_CIN_Client_1_verso', models.FileField(blank=True, upload_to='images')),
                ('tel_client_1', models.CharField(blank=True, max_length=50)),
                ('num_BL', models.CharField(blank=True, max_length=500)),
                ('num_sur_facture', models.CharField(blank=True, max_length=500)),
                ('nom_client_2', models.CharField(blank=True, max_length=50)),
                ('tel_client_2', models.CharField(blank=True, max_length=50)),
                ('PJ_CIN_Client_2_recto', models.FileField(blank=True, upload_to='images')),
                ('PJ_CIN_Client_2_verso', models.FileField(blank=True, upload_to='images')),
                ('montant_reparation', models.IntegerField(null=True)),
                ('motif_reparation', models.TextField(blank=True)),
            ],
        ),
    ]
