# Generated by Django 3.0.6 on 2020-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('datepick', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
