# Generated by Django 2.2.13 on 2020-07-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSelect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Flower')),
            ],
        ),
    ]
