# Generated by Django 2.2.13 on 2020-06-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellee', models.CharField(max_length=500)),
                ('date', models.DateField(null=True)),
                ('depense', models.IntegerField(default='0')),
                ('recette', models.IntegerField(default='0')),
                ('PJ', models.FileField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldeInitial', models.IntegerField(default='0')),
                ('soldeActuel', models.IntegerField(default='0')),
            ],
        ),
    ]
