# Generated by Django 3.0.8 on 2020-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseTana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='depense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='recette',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
