# Generated by Django 3.0.8 on 2020-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseTana', '0003_auto_20200825_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='soldeActuel',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='solde',
            name='soldeInitial',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True),
        ),
    ]
